[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.27"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 200
via_ir = true
ignored_error_codes = [5740]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
taiko_testnet = "https://rpc.test.taiko.xyz"
taiko_mainnet = "https://rpc.taiko.xyz"

[etherscan]
taiko_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://blockscoutapi.test.taiko.xyz/api" }
taiko_mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://blockscoutapi.taiko.xyz/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
